### ISSUE TITLE
snap version of bottom doesn't show Memory and some other sections

### ISSUE THREAD

**Issue by charlesritchea** [kz6fittycent/bottom#2]
I'm on Ubuntu 22.04. Tried to use snap version of bottom, but the memory and I think maybe Disk panes were empty, so I switched to deb version and it works. I suspect it's some sandboxing issue

**Comment by charlesritchea** [comment]
![image](https://user-images.githubusercontent.com/1656349/167858608-9d5d4361-d852-4d04-87ca-fdff3e675e02.png)

**Comment by kz6fittycent** [comment]
Please be sure that the connections are set for the snap:

```
- sudo snap connect bottom:mount-observe
- sudo snap connect bottom:hardware-observe
- sudo snap connect bottom:system-observe
- sudo snap connect bottom:process-control
```

![image](https://user-images.githubusercontent.com/14829816/167873697-df1c1396-24f1-4d7d-9c87-e781edadb4de.png)
